#! /bin/bash
pushd $(dirname "$0")

OUT="public/files"

# Update allergies
curl https://raw.githubusercontent.com/jackcogdill/Food-Allergies/master/README.md > src/other/allergies.md

# Update resume pdf
curl https://raw.githubusercontent.com/jackcogdill/Resume/master/cv.tex > cv.tex
xelatex -output-directory=$OUT cv.tex
rm cv.tex
# Delete files generated by xelatex
rm $OUT/cv.aux
rm $OUT/cv.log
rm $OUT/cv.out
rm $OUT/texput.log

popd
